name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Deploy to Vercel
      if: success()
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Required
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Required
        github-token: ${{ secrets.GITHUB_TOKEN }} # Optional, used for commenting pull requests
